WorldOfWarshipsAcademy/Models/AircraftCarriers.cs
using System;
using System.Collections.Generic;

namespace WorldOfWarshipsAcademy.Models
{
    public partial class AircraftCarriers
    {
        public int Id { get; set; }
        public string Abbrev { get; set; }
        public string Nation { get; set; }
        public string Tier { get; set; }
        public string ShipName { get; set; }
        public int? Survivability { get; set; }
        public int? Aircraft { get; set; }
        public int? Artillery { get; set; }
        public int? AaDefense { get; set; }
        public int? Maneuverability { get; set; }
        public int? Concealment { get; set; }
        public string ImagePath { get; set; }

        public virtual ShipClasses AbbrevNavigation { get; set; }
        public virtual ShipNations NationNavigation { get; set; }
    }
}

WorldOfWarshipsAcademy/Controllers/AircraftCarriersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class AircraftCarriersController : Controller
    {
        private readonly WorldOfWarshipsDbContext _context;

        public AircraftCarriersController(WorldOfWarshipsDbContext context)
        {
            _context = context;
        }

        // GET: AircraftCarriers
        public async Task<IActionResult> Index(string searchString)
        {

            //var worldOfWarshipsDbContext = _context.AircraftCarriers.Include(b => b.AbbrevNavigation).Include(b => b.NationNavigation);
            //return View(await worldOfWarshipsDbContext.ToListAsync());

            var carriers = from ac in _context.AircraftCarriers
                           select ac;

            if (!String.IsNullOrEmpty(searchString))
            {
                carriers = carriers.Where(s => s.ShipName.Contains(searchString));
            }

            return View(await carriers.ToListAsync());

           
        }

        // GET: AircraftCarriers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var aircraftCarriers = await _context.AircraftCarriers
                .Include(a => a.AbbrevNavigation)
                .Include(a => a.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            
            if (aircraftCarriers == null)
            {
                return NotFound();
            }

            return View(aircraftCarriers);
        }

        // GET: AircraftCarriers/Create
        public IActionResult Create()
        {
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation");
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev");
            return View();
        }

        // POST: AircraftCarriers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Abbrev,Nation,Tier,ShipName,Survivability,Aircraft,Artillery,AaDefense,Maneuverability,Concealment")] AircraftCarriers aircraftCarriers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aircraftCarriers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", aircraftCarriers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", aircraftCarriers.Nation);
            return View(aircraftCarriers);
        }

        // GET: AircraftCarriers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aircraftCarriers = await _context.AircraftCarriers.FindAsync(id);
            if (aircraftCarriers == null)
            {
                return NotFound();
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", aircraftCarriers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", aircraftCarriers.Nation);
            return View(aircraftCarriers);
        }

        // POST: AircraftCarriers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Abbrev,Nation,Tier,ShipName,Survivability,Aircraft,Artillery,AaDefense,Maneuverability,Concealment")] AircraftCarriers aircraftCarriers)
        {
            if (id != aircraftCarriers.Abbrev)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aircraftCarriers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AircraftCarriersExists(aircraftCarriers.Abbrev))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", aircraftCarriers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", aircraftCarriers.Nation);
            return View(aircraftCarriers);
        }

        // GET: AircraftCarriers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aircraftCarriers = await _context.AircraftCarriers
                .Include(a => a.AbbrevNavigation)
                .Include(a => a.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (aircraftCarriers == null)
            {
                return NotFound();
            }

            return View(aircraftCarriers);
        }

        // POST: AircraftCarriers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var aircraftCarriers = await _context.AircraftCarriers.FindAsync(id);
            _context.AircraftCarriers.Remove(aircraftCarriers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AircraftCarriersExists(string id)
        {
            return _context.AircraftCarriers.Any(e => e.Abbrev == id);
        }
    }
}

WorldOfWarshipsAcademy/Views/AircraftCarriers/Create.cshtml
@model WorldOfWarshipsAcademy.Models.AircraftCarriers

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AircraftCarriers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Abbrev" class="control-label"></label>
                <select asp-for="Abbrev" class ="form-control" asp-items="ViewBag.Abbrev"></select>
            </div>
            <div class="form-group">
                <label asp-for="Nation" class="control-label"></label>
                <select asp-for="Nation" class ="form-control" asp-items="ViewBag.Nation"></select>
            </div>
            <div class="form-group">
                <label asp-for="Tier" class="control-label"></label>
                <input asp-for="Tier" class="form-control" />
                <span asp-validation-for="Tier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipName" class="control-label"></label>
                <input asp-for="ShipName" class="form-control" />
                <span asp-validation-for="ShipName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Survivability" class="control-label"></label>
                <input asp-for="Survivability" class="form-control" />
                <span asp-validation-for="Survivability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aircraft" class="control-label"></label>
                <input asp-for="Aircraft" class="form-control" />
                <span asp-validation-for="Aircraft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artillery" class="control-label"></label>
                <input asp-for="Artillery" class="form-control" />
                <span asp-validation-for="Artillery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AaDefense" class="control-label"></label>
                <input asp-for="AaDefense" class="form-control" />
                <span asp-validation-for="AaDefense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maneuverability" class="control-label"></label>
                <input asp-for="Maneuverability" class="form-control" />
                <span asp-validation-for="Maneuverability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Concealment" class="control-label"></label>
                <input asp-for="Concealment" class="form-control" />
                <span asp-validation-for="Concealment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorldOfWarshipsAcademy/Views/AircraftCarriers/Delete.cshtml
@model WorldOfWarshipsAcademy.Models.AircraftCarriers

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AircraftCarriers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Survivability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Survivability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aircraft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aircraft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artillery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artillery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AaDefense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AaDefense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maneuverability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maneuverability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Concealment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Concealment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbbrevNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbbrevNavigation.Abbreviation)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationNavigation.NationAbbrev)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Abbrev" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WorldOfWarshipsAcademy/Views/AircraftCarriers/Details.cshtml
@model WorldOfWarshipsAcademy.Models.AircraftCarriers

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AircraftCarriers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Survivability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Survivability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aircraft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aircraft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artillery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artillery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AaDefense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AaDefense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maneuverability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maneuverability)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Concealment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Concealment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbbrevNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbbrevNavigation.Abbreviation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationNavigation.NationAbbrev)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Abbrev">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WorldOfWarshipsAcademy/Views/AircraftCarriers/Edit.cshtml
@model WorldOfWarshipsAcademy.Models.AircraftCarriers

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AircraftCarriers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Abbrev" />
            <div class="form-group">
                <label asp-for="Nation" class="control-label"></label>
                <select asp-for="Nation" class="form-control" asp-items="ViewBag.Nation"></select>
                <span asp-validation-for="Nation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tier" class="control-label"></label>
                <input asp-for="Tier" class="form-control" />
                <span asp-validation-for="Tier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipName" class="control-label"></label>
                <input asp-for="ShipName" class="form-control" />
                <span asp-validation-for="ShipName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Survivability" class="control-label"></label>
                <input asp-for="Survivability" class="form-control" />
                <span asp-validation-for="Survivability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aircraft" class="control-label"></label>
                <input asp-for="Aircraft" class="form-control" />
                <span asp-validation-for="Aircraft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artillery" class="control-label"></label>
                <input asp-for="Artillery" class="form-control" />
                <span asp-validation-for="Artillery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AaDefense" class="control-label"></label>
                <input asp-for="AaDefense" class="form-control" />
                <span asp-validation-for="AaDefense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maneuverability" class="control-label"></label>
                <input asp-for="Maneuverability" class="form-control" />
                <span asp-validation-for="Maneuverability" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Concealment" class="control-label"></label>
                <input asp-for="Concealment" class="form-control" />
                <span asp-validation-for="Concealment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorldOfWarshipsAcademy/Views/AircraftCarriers/Index.cshtml
@model IEnumerable<WorldOfWarshipsAcademy.Models.AircraftCarriers>

@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-image: url('https://miro.medium.com/max/1200/1*2eUGbqPEKciO7twv-mS3jQ.jpeg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Warships Academy</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

</head>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">Warships Academy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form asp-controller="AircraftCarriers" asp-action="Index">
            <p>
                SEARCH: <input type="text" name="SearchString">
                <input type="submit" value="Filter" />
            </p>
        </form>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">
                        Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="About">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<body class="align-content-center">
    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h4 class="display-4 text-center"><strong>Aircraft Carriers</strong></h4>
        </header>
        <table class="table">
            <thead class="jumbotron my-4 text-center">
                <tr>
                    <th class="align-content-center">
                        Image
                    </th>
                    <th class="align-content-center">
                        Tier
                    </th>
                    <th class="align-content-center">
                        Ship Name
                    </th>
                    <th class="align-content-center">
                        Survivability
                    </th>
                    <th class="align-content-center">
                        Aircraft
                    </th>
                    <th class="align-content-center">
                        Artillery
                    </th>
                    <th class="align-content-center">
                        AA Defense
                    </th>
                    <th class="align-content-center">
                        Maneuverability
                    </th>
                    <th class="align-content-center">
                        Concealment
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="jumbotron my-4 text-center">
                @foreach (var item in Model)
                {
                    <container>
                        <tr>
                            <td class="align-content-center">
                                <img src="@Html.DisplayFor(modelItem => item.ImagePath)" height="75" />
                            </td>
                            <td class="align-content-center">
                                @item.Tier
                            </td>
                            <td class="align-content-center">
                                @item.ShipName
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.Survivability)
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.Aircraft)
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.Artillery)
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.AaDefense)
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.Maneuverability)
                            </td>
                            <td class="align-content-center">
                                @Html.DisplayFor(modelItem => item.Concealment)
                            </td>
                            <td class="align-content-lg-center">
                                <a asp-action="Details" asp-route-id="@item.Abbrev">Details</a>
                            </td>
                        </tr>
                    </container>
                }
            </tbody>
        </table>
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Warships Academy 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>