WorldOfWarshipsAcademy/Controllers/BattleshipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class BattleshipsController : Controller
    {
        private readonly WorldOfWarshipsDbContext _context;

        public BattleshipsController(WorldOfWarshipsDbContext context)
        {
            _context = context;
        }

        // GET: Battleships
        public async Task<IActionResult> Index(string searchString)
        {
            //var worldOfWarshipsDbContext = _context.Battleships.Include(b => b.AbbrevNavigation).Include(b => b.NationNavigation);
            //return View(await worldOfWarshipsDbContext.ToListAsync());

            var battleship = from bb in _context.Battleships
                           select bb;

            if (!String.IsNullOrEmpty(searchString))
            {
                battleship = battleship.Where(s => s.ShipName.Contains(searchString));
            }

            return View(await battleship.ToListAsync());
        }

        // GET: Battleships/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var battleships = await _context.Battleships
                .Include(b => b.AbbrevNavigation)
                .Include(b => b.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (battleships == null)
            {
                return NotFound();
            }

            return View(battleships);
        }

        // GET: Battleships/Create
        public IActionResult Create()
        {
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation");
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev");
            return View();
        }

        // POST: Battleships/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] Battleships battleships)
        {
            if (ModelState.IsValid)
            {
                _context.Add(battleships);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", battleships.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", battleships.Nation);
            return View(battleships);
        }

        // GET: Battleships/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var battleships = await _context.Battleships.FindAsync(id);
            if (battleships == null)
            {
                return NotFound();
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", battleships.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", battleships.Nation);
            return View(battleships);
        }

        // POST: Battleships/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] Battleships battleships)
        {
            if (id != battleships.Abbrev)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(battleships);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BattleshipsExists(battleships.Abbrev))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", battleships.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", battleships.Nation);
            return View(battleships);
        }

        // GET: Battleships/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var battleships = await _context.Battleships
                .Include(b => b.AbbrevNavigation)
                .Include(b => b.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (battleships == null)
            {
                return NotFound();
            }

            return View(battleships);
        }

        // POST: Battleships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var battleships = await _context.Battleships.FindAsync(id);
            _context.Battleships.Remove(battleships);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BattleshipsExists(string id)
        {
            return _context.Battleships.Any(e => e.Abbrev == id);
        }
    }
}

WorldOfWarshipsAcademy/Controllers/CruiserClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class CruiserClassesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WorldOfWarshipsAcademy/Controllers/DestroyersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class DestroyersController : Controller
    {
        private readonly WorldOfWarshipsDbContext _context;

        public DestroyersController(WorldOfWarshipsDbContext context)
        {
            _context = context;
        }

        // GET: Destroyers
        public async Task<IActionResult> Index(string searchString)
        {
            //var worldOfWarshipsDbContext = _context.Destroyers.Include(d => d.AbbrevNavigation).Include(d => d.NationNavigation);
            //return View(await worldOfWarshipsDbContext.ToListAsync());

            var destroyer = from dd in _context.Destroyers
                             select dd;

            if (!String.IsNullOrEmpty(searchString))
            {
                destroyer = destroyer.Where(s => s.ShipName.Contains(searchString));
            }

            return View(await destroyer.ToListAsync());
        }

        // GET: Destroyers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destroyers = await _context.Destroyers
                .Include(d => d.AbbrevNavigation)
                .Include(d => d.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (destroyers == null)
            {
                return NotFound();
            }

            return View(destroyers);
        }

        // GET: Destroyers/Create
        public IActionResult Create()
        {
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation");
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev");
            return View();
        }

        // POST: Destroyers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] Destroyers destroyers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destroyers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", destroyers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", destroyers.Nation);
            return View(destroyers);
        }

        // GET: Destroyers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destroyers = await _context.Destroyers.FindAsync(id);
            if (destroyers == null)
            {
                return NotFound();
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", destroyers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", destroyers.Nation);
            return View(destroyers);
        }

        // POST: Destroyers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] Destroyers destroyers)
        {
            if (id != destroyers.Abbrev)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destroyers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestroyersExists(destroyers.Abbrev))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", destroyers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", destroyers.Nation);
            return View(destroyers);
        }

        // GET: Destroyers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destroyers = await _context.Destroyers
                .Include(d => d.AbbrevNavigation)
                .Include(d => d.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (destroyers == null)
            {
                return NotFound();
            }

            return View(destroyers);
        }

        // POST: Destroyers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var destroyers = await _context.Destroyers.FindAsync(id);
            _context.Destroyers.Remove(destroyers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestroyersExists(string id)
        {
            return _context.Destroyers.Any(e => e.Abbrev == id);
        }
    }
}

WorldOfWarshipsAcademy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }      
    }
}

WorldOfWarshipsAcademy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
body { background-image: url('https://miro.medium.com/max/1200/1*2eUGbqPEKciO7twv-mS3jQ.jpeg'); background-repeat: no-repeat; background-attachment: fixed; background-size: 100% 100%; }
</style>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Warships Academy</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Warships Academy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="About">About</a>
                    </li>                   
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h4 class="display-4 text-center"><strong>Classes</strong></h4>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/3/30/Wows-aircarrier.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="AircraftCarriers"><strong>Aircraft Carriers</strong></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/7/77/Wows-battleship.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="Battleships"><strong>Battleships</strong></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/6/60/Wows-cruiser.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="CruiserClasses"><strong>Cruisers</strong></a>                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/8/85/Wows-destroyer.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="Destroyers"><strong>Destroyers</strong></a>
                    </div>
                </div>
            </div>            
        </div>
   </div>
    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h4 class="display-4 text-center"><strong>Nations</strong></h4>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://cdn.countryflags.com/thumbs/united-states-of-america/flag-wave-250.png" alt="">
                    <div class="card-body">
                        <h4 class="card-title">United States Navy</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://cdn.countryflags.com/thumbs/japan/flag-wave-250.png" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Imperial Japanese Navy</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://cdn.countryflags.com/thumbs/germany/flag-wave-250.png" alt="">
                    <div class="card-body">
                        <h4 class="card-title">German Kriegsmarine</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://cdn.countryflags.com/thumbs/united-kingdom/flag-wave-250.png" alt="">
                    <div class="card-body">
                        <h4 class="card-title">British Royal Navy</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://cdn.countryflags.com/thumbs/russia/flag-wave-250.png" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Russian Navy</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images.squarespace-cdn.com/content/v1/5ba5d4bce5f7d1371dd93916/1538330115654-1V19SYVKRS6IX5P1VVG0/ke17ZwdGBToddI8pDm48kDFgITcRoterXoQdllT5ciUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcV7ZyRJyI8bwZiMJRrgPaAKqUaXS0tb9q_dTyNVba_kClt3J5x-w6oTQbPni4jzRa/coming+soon.jpg?format=1500w" alt="">
                    <div class="card-body">
                        <h4 class="card-title">France</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images.squarespace-cdn.com/content/v1/5ba5d4bce5f7d1371dd93916/1538330115654-1V19SYVKRS6IX5P1VVG0/ke17ZwdGBToddI8pDm48kDFgITcRoterXoQdllT5ciUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcV7ZyRJyI8bwZiMJRrgPaAKqUaXS0tb9q_dTyNVba_kClt3J5x-w6oTQbPni4jzRa/coming+soon.jpg?format=1500w" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Pan European Navies</h4>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images.squarespace-cdn.com/content/v1/5ba5d4bce5f7d1371dd93916/1538330115654-1V19SYVKRS6IX5P1VVG0/ke17ZwdGBToddI8pDm48kDFgITcRoterXoQdllT5ciUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcV7ZyRJyI8bwZiMJRrgPaAKqUaXS0tb9q_dTyNVba_kClt3J5x-w6oTQbPni4jzRa/coming+soon.jpg?format=1500w" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Italian Regiana Marina</h4>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Warships Academy 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>