WorldOfWarshipsAcademy/Controllers/CruiserClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class CruiserClassesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WorldOfWarshipsAcademy/Controllers/HeavyCruisersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class HeavyCruisersController : Controller
    {
        private readonly WorldOfWarshipsDbContext _context;

        public HeavyCruisersController(WorldOfWarshipsDbContext context)
        {
            _context = context;
        }

        // GET: HeavyCruisers
        public async Task<IActionResult> Index(string searchString)
        {
            //var worldOfWarshipsDbContext = _context.HeavyCruisers.Include(h => h.AbbrevNavigation).Include(h => h.NationNavigation);
            //return View(await worldOfWarshipsDbContext.ToListAsync());

            var hCruisers = from ca in _context.HeavyCruisers
                            select ca;

            if (!String.IsNullOrEmpty(searchString))
            {
                hCruisers = hCruisers.Where(s => s.ShipName.Contains(searchString));
            }

            return View(await hCruisers.ToListAsync());
        }

        // GET: HeavyCruisers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var heavyCruisers = await _context.HeavyCruisers
                .Include(h => h.AbbrevNavigation)
                .Include(h => h.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (heavyCruisers == null)
            {
                return NotFound();
            }

            return View(heavyCruisers);
        }

        // GET: HeavyCruisers/Create
        public IActionResult Create()
        {
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation");
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev");
            return View();
        }

        // POST: HeavyCruisers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] HeavyCruisers heavyCruisers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(heavyCruisers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", heavyCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", heavyCruisers.Nation);
            return View(heavyCruisers);
        }

        // GET: HeavyCruisers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var heavyCruisers = await _context.HeavyCruisers.FindAsync(id);
            if (heavyCruisers == null)
            {
                return NotFound();
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", heavyCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", heavyCruisers.Nation);
            return View(heavyCruisers);
        }

        // POST: HeavyCruisers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] HeavyCruisers heavyCruisers)
        {
            if (id != heavyCruisers.Abbrev)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(heavyCruisers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HeavyCruisersExists(heavyCruisers.Abbrev))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", heavyCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", heavyCruisers.Nation);
            return View(heavyCruisers);
        }

        // GET: HeavyCruisers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var heavyCruisers = await _context.HeavyCruisers
                .Include(h => h.AbbrevNavigation)
                .Include(h => h.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (heavyCruisers == null)
            {
                return NotFound();
            }

            return View(heavyCruisers);
        }

        // POST: HeavyCruisers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var heavyCruisers = await _context.HeavyCruisers.FindAsync(id);
            _context.HeavyCruisers.Remove(heavyCruisers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HeavyCruisersExists(string id)
        {
            return _context.HeavyCruisers.Any(e => e.Abbrev == id);
        }
    }
}

WorldOfWarshipsAcademy/Controllers/LightCruisersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorldOfWarshipsAcademy.Models;

namespace WorldOfWarshipsAcademy.Controllers
{
    public class LightCruisersController : Controller
    {
        private readonly WorldOfWarshipsDbContext _context;

        public LightCruisersController(WorldOfWarshipsDbContext context)
        {
            _context = context;
        }

        // GET: LightCruisers
        public async Task<IActionResult> Index(string searchString)
        {
            //var worldOfWarshipsDbContext = _context.LightCruisers.Include(l => l.AbbrevNavigation).Include(l => l.NationNavigation);
            //return View(await worldOfWarshipsDbContext.ToListAsync());

            var lCruisers = from cl in _context.LightCruisers
                            select cl;

            if (!String.IsNullOrEmpty(searchString))
            {
                lCruisers = lCruisers.Where(s => s.ShipName.Contains(searchString));
            }

            return View(await lCruisers.ToListAsync());
        }

        // GET: LightCruisers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lightCruisers = await _context.LightCruisers
                .Include(l => l.AbbrevNavigation)
                .Include(l => l.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (lightCruisers == null)
            {
                return NotFound();
            }

            return View(lightCruisers);
        }

        // GET: LightCruisers/Create
        public IActionResult Create()
        {
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation");
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev");
            return View();
        }

        // POST: LightCruisers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] LightCruisers lightCruisers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lightCruisers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", lightCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", lightCruisers.Nation);
            return View(lightCruisers);
        }

        // GET: LightCruisers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lightCruisers = await _context.LightCruisers.FindAsync(id);
            if (lightCruisers == null)
            {
                return NotFound();
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", lightCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", lightCruisers.Nation);
            return View(lightCruisers);
        }

        // POST: LightCruisers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Abbrev,Nation,Tier,ShipName,Survivability,Artillery,Torpedoes,AaDefense,Maneuverability,Concealment")] LightCruisers lightCruisers)
        {
            if (id != lightCruisers.Abbrev)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lightCruisers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LightCruisersExists(lightCruisers.Abbrev))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Abbrev"] = new SelectList(_context.ShipClasses, "Abbreviation", "Abbreviation", lightCruisers.Abbrev);
            ViewData["Nation"] = new SelectList(_context.ShipNations, "NationAbbrev", "NationAbbrev", lightCruisers.Nation);
            return View(lightCruisers);
        }

        // GET: LightCruisers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lightCruisers = await _context.LightCruisers
                .Include(l => l.AbbrevNavigation)
                .Include(l => l.NationNavigation)
                .FirstOrDefaultAsync(m => m.Abbrev == id);
            if (lightCruisers == null)
            {
                return NotFound();
            }

            return View(lightCruisers);
        }

        // POST: LightCruisers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var lightCruisers = await _context.LightCruisers.FindAsync(id);
            _context.LightCruisers.Remove(lightCruisers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LightCruisersExists(string id)
        {
            return _context.LightCruisers.Any(e => e.Abbrev == id);
        }
    }
}

WorldOfWarshipsAcademy/Views/CruiserClasses/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-image: url('https://miro.medium.com/max/1200/1*2eUGbqPEKciO7twv-mS3jQ.jpeg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Warships Academy</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Warships Academy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="About">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h4 class="display-4 text-center"><strong>Cruisers</strong></h4>
        </header>

        <!-- Page Features -->
        <div class="row text-center">
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/6/60/Wows-cruiser.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="HeavyCruisers"><strong>Heavy Cruisers</strong></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="https://wiki.gcdn.co/images/6/60/Wows-cruiser.png" alt="">
                    <div class="card-body">
                        <a asp-action="Index" asp-controller="LightCruisers"><strong>Light Cruisers</strong></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Warships Academy 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>